# Часть 1.

In [9]:
import numpy as np

ЗАДАНИЕ 1.

1. Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

а) A*B или В*A = 4×2 и 4х2 - произведения не определены.

б) A*B = 2×5 и 5×3 - произведение определено, размерность полученной матрицы = 2х3.
   
   B*A = 5х3 и 2х5 - произведение не определено.

в) A*B = 8х3 и 3х8 - произведение определено, размерность полученной матрицы = 8х8.
   
   B*A = 3х8 и 8х3 - произведение определено, размерность полученной матрицы = 3х3.

г) A*B или B*A = 4х4 и 4х4 - произведения определены, размерность полученных матриы = 4х4.

ЗАДАНИЕ 2.

Найдите сумму и произведение матриц  𝐴=(13−20)  и  𝐵=(40−15).

In [10]:
x = np.array([[1,-2], [3,0]])
y = np.array([[4,-1], [0,5]])
result2_1 = x + y
result2_1

array([[ 5, -3],
       [ 3,  5]])

In [11]:
result2_2 = np.dot(x, y)
result2_2

array([[  4, -11],
       [ 12,  -3]])

ЗАДАНИЕ 3.

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц  𝐴=(137−6) ,  𝐵=(025−1) ,  𝐶=(21−41).

In [12]:
x = np.array([[1,7], [3,-6]])
y = np.array([[0,5], [2,-1]])
z = np.array([[2,-4], [1,1]])
result3 = (3 * x) + (-2 * y) + (4 * z)
result3

array([[ 11,  -5],
       [  9, -12]])

ЗАДАНИЕ 4.

Дана матрица  𝐴=[[4,1] [5,-2] [2,3]]. Вычислите  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [13]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [14]:
result4_1 = np.dot(a, aT)
result4_1

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [15]:
result4_2 = np.dot(aT, a)
result4_2

array([[45,  0],
       [ 0, 14]])

ЗАДАНИЕ 5* - не выполнено.

# Часть 2.

In [17]:
import numpy as np

ЗАДАНИЕ 1.

1. Вычислите определитель:

a) [[𝑠𝑖𝑛𝑥,-𝑐𝑜𝑠𝑥] [𝑐𝑜𝑠𝑥,𝑠𝑖𝑛𝑥]];
 
б) [[4, 2, 3] [0,5,1] [009]];
 
в) [[1,2,3] [4,5,6] [7,8,9]].

а) det = sinx*sinx - (cosx * (-cosX)) = sin²x + cos²x = 1

б) :

In [18]:
a1_2 = np.array([[4,2,3], [0,5,1], [0,0,9]])
det1_2 = np.linalg.det(a1_2)
det1_2

180.0

в):

In [19]:
a1_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
det1_3 = np.linalg.det(a1_3)
det1_3

-9.51619735392994e-16

ЗАДАНИЕ 2. 

Определитель матрицы  𝐴  равен  4 . Найдите:

а)  𝑑𝑒𝑡(𝐴2) ;

б)  𝑑𝑒𝑡(𝐴𝑇) ;

в)  𝑑𝑒𝑡(2𝐴) .

а) det(A²) = det(AA) = det(A) * det(a) = 4 * 4 = 16.

б) det(AT) = det(A) = 4.

в) det(2A) = det(A) * 2ⁿ = 4 * 2ⁿ (где n - количество строк в матрице).

ЗАДАНИЕ 3.

Докажите, что матрица [[-2,7,-3] [4,-14,6] [-3,7,13]] вырожденная.

In [20]:
a3 = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
det3 = np.linalg.det(a3)
det3

0.0

Так как определитель матрицы равен "0" - заданная матрица вырожденная.

ЗАДАНИЕ 4.

Найдите ранг матрицы:
а) [[1,2,3] [1,1,1] [2,3,4]]

б) [[0,0,2,1] [0,0,2,2,] [0,0,4,3] [2,3,5,6]]

a):

In [23]:
a = np.array([[1,2,3], [1,1,1], [2,3,4]])
resulta = np.linalg.matrix_rank(a4_1)
resulta

2

б):

In [24]:
b = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
resultb = np.linalg.matrix_rank(a4_2)
resultb

3